name: Import Amazon

on:
  schedule:
    - cron: "00 21 * * *"
  workflow_dispatch:

permissions:
  contents: read
  actions: write

concurrency:
  group: "scraper-phonehouse"
  cancel-in-progress: true

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar librerías
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 woocommerce lxml pillow
          python -m pip install --upgrade pip
          pip install selenium Pillow woocommerce requests beautifulsoup4

      - name: Mostrar archivos del repositorio
        run: |
          echo ">>> LISTADO DE ARCHIVOS:"
          ls -R .

      - name: Ejecutar Script PhoneHouse
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_KEY: ${{ secrets.WP_KEY }}
          WP_SECRET: ${{ secrets.WP_SECRET }}
          PHONEHOUSE_URL: ${{ secrets.SOURCE_URL_AMAZON }}
          AFF_PHONEHOUSE: ${{ secrets.AFF_AMAZON }}
          SOURCE_URL_PHONEHOUSE: ${{ secrets.SOURCE_URL_AMAZON }}
        run: |
          echo ">>> EJECUTANDO amazon.py..."
          python -u amazon.py

      - name: Borrar historiales antiguos
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 6
